name: Output information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output GitHub context
        run: echo "${{ toJson(github) }}"
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Output information
        run: |
          echo "Outputting information..."
          echo "Information outputted!"